Manejo de error con variable de entorno

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,12 +44,13 @@ jobs:
       - name : Apply migrate
         working-directory: PPDApp
         run : |
-          python manage.py migrate
+          python manage.py migrate || echo "migrate_failed=true" >> $GITHUB_ENV
         continue-on-error: true
-      - name: Handle failure
-        if: ${{ failure() }}
+      - name: Handle migration failure
+        if: env.migrate_failed == 'true'
         working-directory: PPDApp
         run: |
+          echo "¡Error en las migraciones! Ejecutando paso correctivo..."
           python manage.py migrate --fake auth
           python manage.py migrate
       - name : Run tests
